[32기 염종은]ADD:login페이지 html,scss 1차 완성
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #1
Opened 2022-05-24 01:34 UTC by Yumjong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 페이지  css,html 완성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
로그인 페이지의 전체적인 UI를 완성했다 (기존 사이트에 로그인 페이지보단 다른 페이지 로그인 페이지 참조)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
로그인 페이지를 만들고 구현을 생각해서 태그를 작성했따

<br />

## :: 기타 질문 및 특이 사항

2022-05-24 01:54 UTC, Yumjong commented on src/pages/jongeun/Login.js
> +            <input className="idInput"></input>
input tag라서 굳이 다른 값을 넣어두지 않았다

2022-05-24 01:54 UTC, Yumjong commented on src/pages/jongeun/Login.js
> +            <input type="password" className="pwInput"></input>
input tag라서 굳이 다른 값을 넣어두지 않았다

2022-05-25 01:33 UTC, younuk23 commented
종은님 
- 브랜치명은 `feature/기능이름` 으로 지어주세요
- 커밋메세지에는 [33기 ~~~~] 적을 필요 없습니다! 커밋 메세지 컨벤션은 일전에 안내해드린 커밋메세지 가이드라인(깃 세션 참고자료) 확인해주세요!

2022-05-25 01:34 UTC, younuk23 commented
PR 본문도 불릿 포인트 사용하는 양식, 최근 작업주제 체크 진행해주세요!

2022-05-25 01:51 UTC, younuk23 requested changes
수고하셨습니다 종은님!
 리뷰 확인 및 반영해주세요~!

2022-05-25 01:51 UTC, younuk23 commented on src/pages/jongeun/Login.js
> +  };
이부분은 실제 백엔드 API가 나오지 않아서 동작하지 않는 부분인 것 같네요, 이상태로 마스터에 머지가 되면 동작하지 않는 코드가 마스터에 머지가 되는것이고 실제 프로젝트 레벨에서는 굉장히 크리티컬한 문제입니다!!

이전 코드들을 참고하는 것은 좋지만 단순 copy & paste가 아닌 참고해서 실제 내가 필요한 부분을 잘 조합해서 활용해주세요!

2022-05-25 01:51 UTC, younuk23 commented on src/pages/jongeun/Login.js
> +    <div>
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetail">
			~~~~
		</section>
	)
}
```

2022-05-25 01:51 UTC, yeonuk-hwang commented on src/pages/jongeun/Login.js
> +          disabled={id.includes('@') && pw.length >= 5 ? false : true}
```suggestion
          disabled={!(id.includes('@') && pw.length >= 5)}
```
삼항연산자를 쓸 필요 없는 부분입니다!!

2022-05-25 01:51 UTC, yeonuk-hwang commented on src/pages/jongeun/Login.js
> +        <div className="inputArea">
semantic tag를 사용할 수 있도록 고민해보세요!
예를들어 이 부분은 input들을 감싸는 태그이니까 div보다 form tag를 활용할수도 있겠네요!

2022-05-25 01:51 UTC, younuk23 commented on src/pages/jongeun/Login.scss
> +@import 'src/styles/reset.scss';
reset은 import 할 필요가 없습니다!
왜 여기서 reset.scss import 할 필요가 없는지 코멘트로 달아주세요!

2022-05-25 01:51 UTC, younuk23 commented on src/pages/jongeun/Login.scss
> +  padding-bottom: 100px;
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://study.wecode.co.kr/session/content/193) 확인하시고 지켜서 작성해주세요

2022-05-25 06:30 UTC, closed without merging