[33기 유하은] Modify: 장바구니리뷰 반영
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #11
Opened 2022-05-25 08:18 UTC by yoohaaeun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- HTML table 요소를 사용하여 장바구니 마크업하기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 장바구니에 상품이 담겨있는경우와 안담겨있는경우 다른 창이 나오게 하기
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- table에 스타일을 적용하기가 너무힘들었다.

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-26 01:54 UTC, younuk23 commented
- 하은님 장바구니 PR branch 이름 바뀌면서 다시 등록하신건가요?? 그러면 해당 부분 리뷰어가 인지할 수 있게 반드시 특이사항에 작성해주세요!!
- 구현 상세 사항 설명은 UI적인 구현 결과물이 아닌, 코드적으로 이걸 어떻게 구현할려고 계획을 세웠고 어떻게 구현했는지에 대한 부분을 작성해주세요!
- 사용하지 않는 기존 PR은 하단의 Close Pull Request 버튼 눌러서 Close 해주세요!

2022-05-26 07:25 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요~!
수정반영하신 부분은 코멘트에 리액션 또는 답글 통해서 반영여부를 확인할 수 있도록 해주세요!

2022-05-26 07:25 UTC, yeonuk-hwang commented on src/index.js
> +import './styles/reset.scss';
reset 두번 import 할 필요 없습니다! 컨플릭트 해결할 때 꼼꼼히 확인 및 push 후에도 File Changed Tab에서 작성한 코드 꼼꼼히 확인해주세요!

2022-05-26 07:25 UTC, younuk23 commented on src/pages/cart/Cart.js
> +  const ITEM_TOTAL = cartList.length;
이 값은 cartList의 값에 따라서 변경되는 값이니까 상수값은 아닙니다! 상수값 네이밍 말고 일반 변수 네이밍에 맞춰서 적용해주세요

2022-05-26 07:25 UTC, yeonuk-hwang commented on src/pages/cart/Cart.js
> +            <CartUI cartList={cartList} itemTotal={ITEM_TOTAL} />
cartList에서 total도 prop으로 받는 것 보다 cartList props의 length를 이용해도 될 것 같네요!

2022-05-26 07:25 UTC, yeonuk-hwang commented on src/pages/cart/Cart.js
> +          {!cartEmpty ? (
👍

2022-05-26 07:25 UTC, younuk23 commented on src/pages/cart/CartUI.js
> +const tableFooter = [
상수데이터는 UPPERCASE + snake_case 로 작성해주는게 프로그래밍 컨벤션입니다!! 다른 개발자들이 봤을 때 이 값은 상수값이구나 라고 이해할 수 있게 컨벤션 잘 지켜서 작성해주세요!!

2022-05-26 07:25 UTC, yeonuk-hwang commented on src/pages/cart/CartUI.js
> +const CartUI = ({ cartList, itemTotal }) => {
컴포넌트는 모두 UI를 표현하는 것이니까 UI등의 단어는 컴포넌트 이름에서 제거해주세요!

2022-05-26 07:25 UTC, yeonuk-hwang commented on src/pages/cart/CartUI.js
> +  const priceArr = [price, shipping, total];
tableFooter가 따로 있고, priceArr와 index를 통해서 맞추는 과정을 거치는 것 보다는, 여기서 
```js
[
  { title: 'Price',  amount:price},
  { title: 'Shipping', amount: shipping},
  { title: 'Total', amount: total },
];
```
등으로 선언해서 사용하는게 추후 요소들이 추가되거나 변경되거나 할 때 좀 더 수정에 용이할 것 같네요!

2022-05-26 07:25 UTC, younuk23 commented on src/pages/cart/CartUI.js
> +            })}
```suggestion
            {tableHeader.map(row => <th key={row}>{row}</th>)}
```
arrow function에서 바로 return 할 경우에는 중괄호 및 return 키워드 생략 가능합니다!

2022-05-26 15:29 UTC, yoohaaeun commented on src/index.js
> +import './styles/reset.scss';
수정했습니다.

2022-05-26 15:40 UTC, yoohaaeun commented on src/pages/cart/Cart.js
> +            <CartUI cartList={cartList} itemTotal={ITEM_TOTAL} />
넵 수정했습니다

2022-05-26 15:42 UTC, yoohaaeun commented on src/pages/cart/CartUI.js
> +const tableFooter = [
넵

2022-05-26 15:46 UTC, yoohaaeun commented on src/pages/cart/CartUI.js
> +const CartUI = ({ cartList, itemTotal }) => {
넵!

2022-05-26 15:49 UTC, yoohaaeun commented on src/pages/cart/CartUI.js
> +            })}
넵!

2022-05-26 15:55 UTC, yoohaaeun commented on src/pages/cart/CartUI.js
> +  const priceArr = [price, shipping, total];
수정했습니다!!

2022-05-27 02:19 UTC, younuk23 requested changes
고생하셨습니다 하은님, 간단하게 반영할 수 있는 사항들 코멘트 남겼습니다 반영해주세요!

2022-05-27 02:19 UTC, younuk23 commented on src/pages/cart/CartNotEmpty.js
> +const tableHeader = [
상수데이터는 UPPERCASE + snake_case 로 작성해주는게 프로그래밍 컨벤션입니다!! 다른 개발자들이 봤을 때 이 값은 상수값이구나 라고 이해할 수 있게 컨벤션 잘 지켜서 작성해주세요!!

리뷰 내용 코멘트 달린 코드말고도 작업내용 전체적으로 적용될 수 있는 부분들은 적용해주세요!

2022-05-27 02:19 UTC, younuk23 commented on src/pages/cart/CartNotEmpty.js
> +  const TABLE_FOOTER = [
```suggestion
  const tableFooter = [
```
이 데이터는 amount가 데이터에 따라서 변하기에 정적인 값이 아닙니다! 정적인 값과 상수데이터 잘 분리해서 생각해주세요!

2022-05-27 02:19 UTC, younuk23 commented on src/index.js
> +import './styles/reset.scss';
👍

2022-05-27 02:19 UTC, younuk23 commented on src/index.js
> +import './styles/reset.scss';
하은님께서 작업하신 내용은 아니겠지만 import 순서 컨벤션 상 common.scss도 Router 컴포넌트 아래에서 import 하는 것으로 같이 수정해주세요!

2022-05-27 02:53 UTC, yoohaaeun commented on src/pages/cart/CartNotEmpty.js
> +  const TABLE_FOOTER = [
넵🥲

2022-05-27 09:06 UTC, younuk23 approved these changes
LGTM 👍

2022-05-27 09:06 UTC, merged