[33기 박슬기] 상품 상세페이지 디자인 및 기능 1차 완료
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #14
Opened 2022-05-26 23:27 UTC by DevSeulgi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 상품 상세페이지 구현
- 구매하기 / 장바구니 페이지 연동
- 상품후기 / 상품문의 페이지 연동
- sns 공유하기

<br />

## :: 구현 사항 설명
**1. 레이아웃 구성**
- width를 각각 60% : 40%로 주어 어느정도의 반응형에 대응할 수 있도록 구현
- 상세페이지 이미지에는 min-width 부여

**2. MockData 사용**
- 상품 이름, 설명, 가격 정보 이용 (재고 수량과 옵션에 따른 UI 구현 진행중)

**3. 상품 수량 선택**
- 1개 이하로 수량 선택 시 alert 구현 ("주문 수량은 1 이상이어야 합니다.")
- 초기값 1로 지정 up, down 버튼을 통해 수량 조절 (숫자칸을 통한 입력 불가 -> 해결필요)
- 선택 수량에 따른 total 가격 및 수량 변화 구현

**4. hover & transition **
- 구매하기 / 장바구니 버튼 hover 시 색상 변경 및 transition
- wish list / 상품후기 / 상품문의 / size 버튼 hover 시 색상 변경

<br />

## :: 성장 포인트
- react-icons의 사용법을 알게되었습니다.
- 단위 표기가 되어 있는 가격은 string이니 별도로 함수를 만들어 처리해야 천원 단위가 표기 된다는 것을 알게 되었습니다.
- 천원 단위 표기법으로 인해 정규식 패턴을 처음 맛보았습니다...

<br />

## :: 기타 질문 및 특이 사항
- 상품 수량 입력하는 곳 input 창 초기값 나오지 않음 & string 더하기가 되어서 div 빈칸으로 만들어 놓았습니다.
기존에 입력했던 Input 창 코드에 뭐가 문제 였던 걸까요 🥲
- Wish List 클릭 시 로그인 비로그인 상태에서의 시나리오가 다른데 로직 처리를 어떻게 해야할지 궁금합니다.
- 상품후기나 상품문의를 선택하면 좌측에서 페이지가 튀어(?)나오는데 modal으로 봐야하는 걸까요...?
![스크린샷 2022-05-27 08 08 14](https://user-images.githubusercontent.com/97112697/170593745-f39ed7d8-75d1-4a23-9b1e-00c359cfd0b3.png)

2022-05-27 02:14 UTC, younuk23 commented
슬기님! 브랜치 이름 변경으로 사용하지 않게 된 PR은 PR 하단은 Close Pull Request 버튼 눌러서 닫아주세요!

2022-05-27 02:19 UTC, DevSeulgi commented
> 슬기님! 브랜치 이름 변경으로 사용하지 않게 된 PR은 PR 하단은 Close Pull Request 버튼 눌러서 닫아주세요!

2022-05-27 02:31 UTC, younuk23 commented
상품 수량 입력하는 곳 input 창 초기값 나오지 않음 & number가 아닌 string 더하기가 되어서 div 빈칸으로 대체 했습니다...
=> input의 value prop 활용해보시면 좋을 것 같아요! 그리고 target.value등으로 가져온 input창에 입력된 값은 string type을 가지고 있습니다. number로 변환하길 원하신다면 how to convert string to number in javascript 등으로 검색해보시면 결과 얻으실 수 있을 것 같아요!

단위 표기 함수가 render 시 바로 price 값을 가져오지 못하고 Cannot read properties of undefined (reading 'toString')에러가 뜹니다...

Wish List 클릭 시 로그인 비로그인 상태에서의 시나리오가 다른데 로직 처리를 어떻게 해야할지 궁금합니다.
=> 로그인 여부를 판별할 수 있는 기준을 하나 세우고, 그 기준값에 따라서 다른 동작으로 분기 처리를 하면 될 것 같네요! 이해안되거나 조금 더 자세한 Q&A 시간에 저 포함 멘토분들에게 질문주시면 될 것 같습니다!

상품후기나 상품문의를 선택하면 좌측에서 페이지가 튀어(?)나오는데 modal으로 봐야하는 걸까요...?
=> 해당 UI는 drawer 등으로 부를 수도 있겠지만 구현 상 큰 원리 자체는 특정 조건에 따라서 UI의 표시 여부를 결정한다는 점에서 Modal과 크게 다르지 않습니다!!

2022-05-27 02:38 UTC, younuk23 requested changes
고생하셨습니다 슬기님, 전반적으로 컨벤션지켜서 깔끔하게 짜려고 하신 모습이 잘 보이네요 👍 
리뷰 확인 및 반영해주세요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +import { IoMdArrowDropup, IoMdArrowDropdown } from 'react-icons/io';
import order convention 맞춰주세요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +  const [list, setList] = useState([]);
list란 변수명 만으로는 어떤 정보를 표현하는지 알 수 없습니다! 항상 이름은 의미가 잘 드러나도록 지어주세요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +    fetch('/Data/ITEM_LIST.json')
폴더명 `/data` 로 수정해주세요!!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +    fetch('/Data/ITEM_LIST.json')
이부분과 밑에 callback 부분 arrow function으로 사용하는 것 기존에 리뷰드렸던 내용 같습니다! 반영해주세요!!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +  const onChange = e => {
함수명도 마찬가지로 onChange 보다는, 어떤 동작을 하는지 명확히 드러나게 지어주세요! 밑의 increaseAmount 등이 아주 좋은 함수명이네요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +    .replace(/\B(?=(\d{3})+(?!\d))/g, ',');
세자리수만다 콤마 찍는 동작이라면 Number.toLocaleString() 메소드가 이미 구현되어 있습니다!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString 참고해보세요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/productDetail/ProductDetail.js
> +    <div>
단순 감싸기 위한 태그라면 Fragment로 처리해도 좋겠네요!

2022-05-27 02:38 UTC, younuk23 commented on src/pages/store/Store.js
> +    setListType(true);
BIg, Small type을 나타내는 것이라면 boolean보다는 "big", "small" 등의 문자열이 state의 값으로 좀 더 적합해보이네요

2022-05-30 02:23 UTC, younuk23 reviewed
LGTM 👍  추가 구현 사항은 어떤건가요?
지금 작업 내용 좋아서, 추가 구현 사항 다른 브랜치에서 진행한다면 이 브랜치는 머지해도 될 것 같습니다!

2022-05-30 02:23 UTC, younuk23 commented on src/pages/store/Store.js
> +    setListType(true);
이거는 적용하시는데 어려움이 있으신건가요? 그렇다면 라이브 코드 리뷰때 이부분 한번 질문 주세요~!

2022-05-30 02:23 UTC, younuk23 commented
컨플릭트 해결해주세요~!

2022-05-30 02:24 UTC, younuk23 commented
저번 백엔드 통신 세션 때는 토큰을 로컬에 저장하는 식으로 진행을 하였는데 실제로는 토큰을 어떻게 관리하는 건지 궁금합니다! (토큰을 발급받았는지 아닌지 어떻게 알 수 있나요?)
=> 토큰을 로컬 또는 세션에 목적에 맞게 저장하시면 됩니다!, 그러면 토큰 발급 여부는 로컬 또는 세션에 토큰이 저장되어있는지 아닌지로 판단할 수 있을 것 같네요!

2022-05-30 04:01 UTC, DevSeulgi commented on src/pages/store/Store.js
> +    setListType(true);
해당 부분 수정해서 feature/store 브런치에 올렸는데 store 브랜치 이름 수정하면서 PR에 문제가 생긴거 같습니다. ㅠㅠ
얘기주신대로 productDetail 브랜치 머지되면 store 쪽 다시 봐주시면 될듯합니다...!

2022-05-30 04:02 UTC, DevSeulgi commented
> LGTM 👍 추가 구현 사항은 어떤건가요? 지금 작업 내용 좋아서, 추가 구현 사항 다른 브랜치에서 진행한다면 이 브랜치는 머지해도 될 것 같습니다!

2022-05-30 10:04 UTC, younuk23 approved these changes
LGTM 👍

2022-05-30 10:04 UTC, merged