[33기 유하은] ADD: 장바구니 기능구현
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #20
Opened 2022-05-28 05:58 UTC by yoohaaeun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

1. 수량버튼을 이용한 기능 구현
2. 체크박스를 이용한 기능구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 수량버튼을 이용한 기능 구현
 - 수량버튼에 onChange이벤트가 일어나면 onChangeQty함수가 실행된다.
 - e.target.value를 quantity state에 저장을 해주고, 수량버튼인 input에 value를 quantity로 지정해준다.
 - cartList를 map으로 돌려서 들어오는 인자들 중 수량이 변경되는 item의 id와 일치할 경우 qty를 변경을 시켜줘서 return하고, 일치하지 않는 경우에는 그냥 return을 시켜줘서 새로운 배열에 담기도록 한다.
- 이 새로운 배열을 cartList state에 저장해준다.
- 각 상품의 total값은 price와 quantity를 곱한 값이 되도록 한다.

2. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-30 02:33 UTC, younuk23 requested changes
고생하셨습니다! 리뷰 확인해주세요!

2022-05-30 02:33 UTC, younuk23 commented on src/pages/cart/CartItem.js
> +  }, [item.qty]);
item의 qty를 그대로 사용하지 않고 quantity라는 state로 따로 만들어서 사용한 이유가 있나요??
만약 특정 이유로 인해서 따로 state를 만든거라면 이대로 진행해도 좋을 것 같고, 아니라면 상위 컴포넌트의 item state를 그대로 수정하는 방식으로 진행하는게 좋을 것 같네요!

2022-05-30 08:43 UTC, ghost commented on src/pages/cart/CartItem.js
> +      console.log('cartItem.id', cartItem.id);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/495294341/pulls/20#issue-6966160))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/495294341/pulls/20#issue-6966160) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-05-31 06:11 UTC, yeonuk-hwang approved these changes
머지하겠습니다!

다음부턴 사이더 코멘트도 꼼꼼히 확인해주세요!

2022-05-31 06:12 UTC, younuk23 commented
컨플릭 해결해주세요!

2022-05-31 09:40 UTC, younuk23 commented
LGTM

2022-05-31 09:40 UTC, merged