[33기 박슬기] Add : store 페이지 기존 작업 업로드
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #3
Opened 2022-05-24 04:24 UTC by DevSeulgi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-25 02:11 UTC, younuk23 requested changes
고생하셨습니다 슬기님 리뷰 확인 및 반영해주세요~!

2022-05-25 02:11 UTC, yeonuk-hwang commented on src/index.js
> +import './styles/variables.scss';
variables 는 index.js에서 import 할 필요 없습니다!
왜 할 필요 없는지 코멘트로 남겨주세요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.js
> +  }, []);
```suggestion
  const [list, setList] = useState({});
  const { itemDetail, itemName, description, price } = list;
  
  useEffect(() => {
    fetch('/Data/ITEM_LIST.json')
      .then(res => res.json())
      .then((result) => setList(result[0]));
  }, []);
```

- list라는 변수명은 어떤 것을 표현하고 있는지 파악하기 힘들어 보입니다!
- 다른 문맥들끼리는 공백 통해서 가독성 신경써주세요
- data 폴더는 소문자로 해주세요!!
  - 깃은 대소문자 추적을 기본적으로 하지 않아서 git mv 명령어를 통해서 대소문자 변경을 알려줘야 합니다.
  - https://dev.to/studentedge/rename-folder-to-lowercase-git-347d 참고해서 진행해보세요(이해 안되거나 어려우시면 라운지 시간에 멘토들에게 질문주세요!)
- 데이터가 배열형태로 오지만 그 중에서 첫번째 요소만 필요할 경우에는 애초에 setState 할 때 첫번째 아이템만 넣어줘도 될 것 같네요!
- 다른 함수의 인자로 들어가는 함수와 같은 경우에는 함수 선언식보다 arrow function 형태가 가독성이 더 좋습니다.

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.js
> +        <img src={itemDetail} alt="img" />
alt에 좀 더 의미있는 정보를 제공해주세요!

img, photo, picture 등의 단어는 이미 img tag이므로 image인 것을 알 수 있기에 넣을 필요가 없습니다!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.js
> +      <section className="rightSide">
leftSide, lightSide 보다는 어떤 정보를 표현하는 섹션인지 className에 드러나는게 더 좋겠네요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +  h2 {
- div 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +    }
```suggestion
  .rightSide {
    width: 45%;
    right: 0;
    
    .sideDetail {
      position: fixed;
      width: 750px;
      padding: 120px 10%;
    }
```
다른 셀렉터들끼리는 공백 부여해주세요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +    .buyBtn {
nesting을 위한 최상위 className을 제외하고는 스타일을 부여하지 않는데 네스팅만을 위해서 className을 부여할 필요는 없습니다!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +    .buyBtn {
라고 작성했는데 padding 을 준게 아래에 있었군요! butBtn의 스타일링은 여기에 적어주는게 덜 헷갈리겠네요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +    }
```suggestion
    .buyBtn {
      padding: 20px 0;
      
      button {
        width: 100%;
        height: 45px;
        margin-bottom: 8px;
        border: 1px solid #ddd;
      }
    }
```

2022-05-25 02:11 UTC, younuk23 commented on src/pages/store/seulgi.js
> +  // const [listType, setListtype] = useState('');
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/store/seulgi.js
> +    <div className="Store">
```suggestion
    <div className="store">
```

2022-05-25 02:11 UTC, younuk23 commented on src/pages/store/seulgi.js
> +          })}
여기도 변수명 신경써주세요!, 그리고 매개변수자리에서 바로 구조분해해주는것도 좋겠네요
```suggestion
          {list.map(({id, state, ~~~~})=> {
            return (
              <Items
                key={list.id}
                state={list.state}
                img={list.itemThumbnail}
                name={list.itemName}
                itemPrice={list.price}
              />
            );
          })}
```

2022-05-25 02:11 UTC, younuk23 commented on src/pages/store/seulgi.js
> +  // };
주석은 위에 코멘트 드린것과 마찬가지입니다! 다른부분도 다 확인해서 반영해주세요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/store/seulgi.js
> +export default Store;
하나의 파일엔 하나의 컴포넌트만 있도록 해주세요!

2022-05-25 02:11 UTC, younuk23 commented on src/pages/productDetail/seulgi.scss
> +  h2 {
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://study.wecode.co.kr/session/content/193) 확인하시고 지켜서 작성해주세요

전반적으로 css order 맞춰주세요!

2022-05-25 02:11 UTC, younuk23 commented
- 커밋메세지에는 [33기 ~~~~] 등 남길 필요 없습니다!
- 추가기능 구현 중 라벨이 부착되어있는데 이 브랜치에서 작업 어느정도 완료된 것 같은데 어떤 추가구현일까요?

2022-05-25 06:10 UTC, DevSeulgi commented on src/index.js
> +import './styles/variables.scss';
다른 scss 파일에서 import 했기 때문인가욥???

2022-05-25 06:58 UTC, FIH36 commented on src/pages/productDetail/seulgi.js
> +  }, []);
멘토님 제가 브랜치 새로 생성 후 왔다갔다하면서 작업을 해서 productDetail 브랜치 부분도 같이 업로드 된 거 같습니다.
해당 부분은 productDetail 브랜치에서 수정해서 올리도록 할게요!

2022-05-27 09:37 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.js
> +      <section className="rightSide">
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:37 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.js
> +        <img src={itemDetail} alt="img" />
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:38 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.js
> +  }, []);
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:38 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.scss
> +  h2 {
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:38 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.scss
> +    }
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:38 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.scss
> +    .buyBtn {
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 09:39 UTC, DevSeulgi commented on src/pages/productDetail/seulgi.scss
> +    }
해당 부분은 productDetail 브랜치에 수정하여 올렸습니다!

2022-05-27 11:15 UTC, closed without merging