[33기 신윤지] Add: 후기 페이지 게시글 컴포넌트 마크업
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #5
Opened 2022-05-24 07:45 UTC by sourmix

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 페이지 내의 게시글 컴포넌트 SCSS까지 완성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 목데이터로 정보 받아오기
- map()을 사용하지 못해 하드코딩을 했다. 
- 목데이터를 아예 쓰지 못한 곳은 게시판내 글을 복사 붙여넣기 했다. 

2. 애니메이션, 후버 처리
- animista를 이용하여 타이틀 애니메이션 추가

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 동일한 목데이터를 사용하는 다른 페이지와 연결 시키는 것을 모르겠습니다
- tale 사용에 대해 구글 검색으로 scss를 처리했습니다. 어렵습니다. 
<br />

## :: 기타 질문 및 특이 사항
- 목데이타에 대한 이해가 부족합니다.

2022-05-24 08:23 UTC, younuk23 requested changes
수고하셨습니다 윤지님! 리뷰 확인 및 반영해주세요! PR 본문에 작업내용도 체크해주세요!

그리고 전반적으로 라운지 때 말씀드린 것 처럼 이미 마크업을 다 해둔것을 다시 변경해서 수정하려면 다소 어려움이 있을 수 있고, 그리고 두번 작업을 하는 것이 될수도 있기에 하드코딩으로 전체 마크업을 다 해둔 뒤에 그걸 다시 컴포넌트화 하고, 상수데이터와 조합하는 것 보다 처음부터 하나하나 컴포넌트화 해서 작업하시는 방향이 더 좋습니다!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/Router.js
> +        <Route path="/reviewPage" element={<Post />} />
URL은 camelCase보다 snake-case로 작성하는게 일반적입니다!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +import { AiOutlineArrowUp, AiOutlineArrowDown } from 'react-icons/ai';
```suggestion
import { AiOutlineArrowUp, AiOutlineArrowDown } from 'react-icons/ai';
import './Post.scss';
```

scss import를 마지막에 해주세요

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +const productInfo = [
상수데이터는 UPPERCASE + snake_case 로 작성해주는게 프로그래밍 컨벤션입니다!! 다른 개발자들이 봤을 때 이 값은 상수값이구나 라고 이해할 수 있게 컨벤션 잘 지켜서 작성해주세요!!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +    <div className="reviewContainer">
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetail">
			~~~~
		</section>
	)
}
```

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +              <span>{productInfo[0].품절 ? '품절' : null}</span>
```suggestion
              <span>{productInfo[0].NEW && 'NEW'}</span>
              <span>{productInfo[0].품절 && '품절'}</span>
```
삼항연산자 말고 && 연산자로도 표현할 수 있어보이네요!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +            </tr>
반복되는 UI로 보이네요, 반복되는 UI는 하드코딩 하는 것 보다 Array.map 메서드를 활용하면 코드가 깔끔해지고, 유지보수에 용이해집니다.

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.scss
> +@import '../styles/variables.scss';
css가 전반적으로 정리가 안되이어있네요! 네스팅 적용해주세요!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.scss
> +}
이렇게 css 작성하시면 모든 a tag에 적용되게 될 것 같네요 만약 모든 a tag에 적용하고 싶다면 common에 있어야 하는 항목으로 보이네요!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.scss
> +}
-webkit들은 지금 불필요한 속성으로 보이네요 삭제해주세요!

2022-05-24 08:23 UTC, yeonuk-hwang commented on src/review/Post.js
> +          <div>{/* <a></a> =>  navigation */}</div>
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-05-25 01:03 UTC, sourmix commented on src/Router.js
> +        <Route path="/reviewPage" element={<Post />} />
수정했습니다!

2022-05-25 01:03 UTC, sourmix commented on src/review/Post.js
> +import { AiOutlineArrowUp, AiOutlineArrowDown } from 'react-icons/ai';
수정완료!

2022-05-25 01:04 UTC, sourmix commented on src/review/Post.js
> +const productInfo = [
수정했습니다!

2022-05-25 01:05 UTC, sourmix commented on src/review/Post.scss
> +}
수정했습니다

2022-05-25 01:06 UTC, sourmix commented on src/review/Post.scss
> +}
삭제했습니다!

2022-05-25 01:07 UTC, sourmix commented on src/review/Post.js
> +    <div className="reviewContainer">
수정했어요!

2022-05-25 04:29 UTC, sourmix commented on src/review/Post.js
> +            </tr>
map 으로 정리했지만 여전히 이해를 못했습니다 ㅠㅠ

2022-05-25 04:34 UTC, sourmix commented on src/review/Post.js
> +              <span>{productInfo[0].품절 ? '품절' : null}</span>
수정했지만 이해를 못했습니다 ㅠㅠ

2022-05-25 04:48 UTC, sourmix commented on src/review/Post.scss
> +@import '../styles/variables.scss';
완료했습니다!

2022-05-25 06:07 UTC, sourmix commented on src/review/Post.js
> +          <div>{/* <a></a> =>  navigation */}</div>
이상하게 수정했습니다

2022-05-25 07:16 UTC, yeonuk-hwang commented on src/review/Post.js
> +            <div>{/* navigation 기능 넣기 근데 주소가 없다*/}</div>
```suggestion
            <div>{/*TODO: 주소 확정되면 Link 컴포넌트 추가*/}</div>
```

2022-05-25 07:16 UTC, younuk23 commented on src/index.js
> +import './styles/reset.scss';
styles/reset.scss 두번 import 하고 있네요 항상 push 후에는 코드 꼼꼼히 확인해주세요!

2022-05-25 07:21 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!

2022-05-25 07:21 UTC, younuk23 commented on src/index.js
> +import './styles/reset.scss';
PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요!

2022-05-25 07:21 UTC, younuk23 commented on src/review/Post.js
> +    fetch('http://localhost:3000/data/relatedProductData.json')
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-05-25 07:21 UTC, younuk23 commented on src/components/review/TextItem.js
> +const TextItem = ({ data }) => {
변수명은 명확하게 의미가 드러나도록 지어주세요. 코드는 쓰여지는 것보다 읽히는 경우가 훨씬 더 많습니다. 이름만 보더라도 어떤 값을 담고 있는 변수인지 알 수 있게 지어주세요

data라는 이름은 어떤 정보를 표현하는지 이름만 보고 전혀 알수가 없습니다

2022-05-25 07:21 UTC, younuk23 commented on src/review/Post.js
> +  const [textList, setTextList] = useState([]);
textList가 어떤 정보를 표현하는 이름인지 파악하기 힘듭니다

2022-05-25 07:21 UTC, younuk23 commented on src/review/Post.js
> +];
굳이 배열에 한번 감싸신 이유가 있나요 바로 객체로 표현해도 될 것 같네요!

2022-05-25 07:21 UTC, younuk23 commented on src/review/Post.scss
> +@import '../styles/variables.scss';
👍

2022-05-25 07:21 UTC, younuk23 commented on src/review/ReviewPage.js
> +            <li></li>
사이더 코멘트 다 해결해주세요

2022-05-25 07:21 UTC, younuk23 commented on src/review/ReviewPage.js
> +    <div className="reviewContainer">
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetail">
			~~~~
		</section>
	)
}
```

2022-05-25 07:21 UTC, younuk23 commented on src/review/Post.js
> +      <div className="Post">
```suggestion
      <div className="post">
```
className은 camelCase 지켜주세요

2022-05-25 07:21 UTC, younuk23 commented on src/review/ReviewPage.scss
> +  }
스타일을 부여하지 않을 거라면 굳이 className을 부여할 필요가 없습니다.

2022-05-25 07:23 UTC, yeonuk-hwang commented
PR 제목은 이 브랜치에서 하고자 한 작업의 목적을 적어주시면 됩니다, 리뷰 반영 할 때마다 수정요청 반영했다고 PR 제목을 변경할 필요는 없습니다!

2022-05-25 09:14 UTC, sourmix commented on src/review/ReviewPage.js
> +            <li></li>
아 reviewPage는 아직 손을 안 댔고 reviewPost에 잘못된 게 있는 가 했습니다

2022-05-25 09:15 UTC, sourmix commented on src/index.js
> +import './styles/reset.scss';
수정했습니다 merge하면서 그렇게 됐을지도 모르겠네요 ;ㅅ;

2022-05-25 09:16 UTC, sourmix commented on src/review/Post.js
> +];
배열로 안 감싸면 인덱스가 없어지지 않나요?

2022-05-26 02:38 UTC, sourmix commented on src/review/ReviewPage.js
> +            <tr></tr>
브랜치 분리 했습니다

2022-05-26 02:39 UTC, sourmix commented on src/review/Post.js
> +            <div>{/* navigation 기능 넣기 근데 주소가 없다*/}</div>
주소기능 추가했습니다

2022-05-26 02:43 UTC, sourmix commented on src/review/Post.js
> +    fetch('http://localhost:3000/data/relatedProductData.json')
반영했습니다!

2022-05-26 02:44 UTC, sourmix commented on src/review/Post.js
> +  const [textList, setTextList] = useState([]);
postList로 수정했습니다!

2022-05-26 02:45 UTC, sourmix commented on src/review/Post.js
> +      <div className="Post">
수정했습니다

2022-05-26 02:45 UTC, sourmix commented on src/review/ReviewPage.scss
> +  }
삭제했습니다

2022-05-26 02:46 UTC, sourmix commented on src/review/ReviewPage.js
> +    <div className="reviewContainer">
브랜치 분리했습니다 ㅠㅠ

2022-05-26 04:52 UTC, sourmix commented on src/components/review/TextItem.js
> +const TextItem = ({ data }) => {
수정했습니다!

2022-05-26 04:53 UTC, sourmix commented on src/review/Post.js
> +      <div className="Post">
가장 바깥 div는 컴포넌트 이름과 같아야 하는 게 아닌가요? ㅠㅠ 수정하니 오류가 나서 일단 다시 돌렸습니다

2022-05-26 07:05 UTC, younuk23 requested changes
리뷰 및 반영해주세요!

2022-05-26 07:05 UTC, younuk23 commented on src/review/Post.js
> +];
인덱스가 굳이 필요한 이유가 있나요?

2022-05-26 07:05 UTC, younuk23 commented on src/review/Post.js
> +      <div className="Post">
컴포넌트 이름과 같되 camelCase 지켜서 작성하도록 가이드 드렸습니다! className을 변경하실 때는 scss도 수정해야지 스타일이 적용되겠죠? 아마 그부분 때문에 오류가 났다고 하신 것 같네요

2022-05-26 07:05 UTC, younuk23 commented
컨플릭트도 해결해주세요!

2022-05-26 08:42 UTC, sourmix commented on src/review/Post.js
> +];
아직 백엔드에서 데이터를 못 넘겨받아서 하드코딩이 필요한 부분이 있더라고요 ㅠㅠ

2022-05-26 09:04 UTC, sourmix commented on src/review/Post.js
> +      <div className="Post">
대소문자로 구분된 post가 존재해서 그랬습니다 ㅠ 수정했습니다

2022-05-27 02:13 UTC, younuk23 commented
![image](https://user-images.githubusercontent.com/54208214/170614941-66955dd9-1e6c-420d-8ade-482cad765d96.png)
Github상에서 main <-> 윤지님 브랜치 간 충돌이 확인됩니다, 로컬에서는 컨플릭트를 발생 시키고 해결하는 과정을 거치지 않았으니 당연히 충돌사항이 보이지 않습니다. Westagram Github Kickoff 세션간 학습했던 내용입니다! 해당 내용 확인해보시고 충돌 해결해주세요!!

2022-05-27 09:09 UTC, younuk23 requested changes
윤지님 바로 반영하실 수 있는 간단한 코멘트 몇개 있습니다, 반영하시면서 컨플릭트도 해결해주세요!

2022-05-27 09:09 UTC, younuk23 commented on src/components/review/TextItem.js
> +const TextItem = ({ postData }) => {
변수명에서 Data등의 접미사는 붙이지 않아도 됩니다!

2022-05-27 09:09 UTC, younuk23 commented on src/components/review/TextItem.js
> +  return (
```suggestion
  const {id, number, ~~~~~} = postData
  return (
```

postData 구조분해할당해서 사용해도 좋겠네요

2022-05-27 09:09 UTC, younuk23 commented on src/review/Post.js
> +};
이 컴포넌트 사이즈가 커서, 자식 컴포넌트별로 분리하는 것도 좋겠네요! 다음 브랜치에서 분리해주세요!

2022-05-27 09:16 UTC, sourmix commented on src/review/Post.js
> +};
알겠습니다 감사합니다

2022-05-27 09:18 UTC, sourmix commented on src/components/review/TextItem.js
> +const TextItem = ({ postData }) => {
수정했습니다

2022-05-27 09:29 UTC, sourmix commented on src/components/review/TextItem.js
> +  return (
수정했습니다

2022-05-27 09:57 UTC, younuk23 commented
윤지님 머지가 되고 싶은 마음은 알겠으나,
***
- 머지는 요청하는 것이 아니라 PR등록했을 때 PR의 코드가 머지될 수 있는 수준이면 자연스럽게 진행됩니다.
- 따라서 완료 라벨은 제가 보고 이 PR이 완료된 수준이라고 판단했을 때 머지하고 나서 부착하는 라벨이라서 검토를 요청할 때는 리뷰요청 라벨을 사용해주세요, 용도에 맞게 라벨을 사용해주셔야 합니다.
- PR 제목은 일전에 가이드 드렸다시피 브랜치에서 의도한 작업을 양식에 맞춰서 한줄 요약해서 작성해주세요!
- 커밋 메세지도 해당 커밋에서 한 작업내용이 드러날 수 있게 작성해주세요.
- 그리고 코드 업데이트 되면 PR 본문도 업데이트 진행해주세요
***
PR 제목, 본문, 라벨 수정해주세요!

2022-05-30 01:05 UTC, younuk23 approved these changes
LGTM 👍

2022-05-30 01:05 UTC, merged