[33기 염종은] Modify: login인 페이지 수정요청 반영
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #8
Opened 2022-05-25 04:25 UTC by Yumjong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
수정요청 사항을 확인하고 수정해서 다시 올렸다

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.branch명 변경
2.불필요한 코드 삭제
3.태그명 변경
4.eset.scss import수정
5.scsss순서 정리

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
내가 평소 그냥 넘어가던 사소한 코드명이나 scss정리 등을 할 수 있게 되었다. 좀 더 신경 써서 할 수 있을꺼 같다
<br />

## :: 기타 질문 및 특이 사항

2022-05-25 07:26 UTC, younuk23 requested changes
PR 제목 및 본문 잘 작성해주셨네요! 👍 
코드상에서 의도하신 목표와 부합하지 않게 동작하는 코드가 있어보이네요, 항상 꼼꼼히 동작 확인하고나서 PR & 리뷰요청 진행해주세요!
그리고 push 하신 후 컨플릭 있는지도 꼼꼼히 확인해주세요!

컨플릭 해결 및 리뷰 반영 진행해주세요~!

2022-05-25 07:26 UTC, younuk23 commented on src/pages/jongeun/Login.js
> +          disabled={id.includes('@') && pw.length >= 5}
조건이 맞을 때 버튼이 비활성화되버릴것 같은데 의도하신 사항과 반대로인 것 같네요

2022-05-25 08:19 UTC, Yumjong commented on src/pages/jongeun/Login.js
> +          disabled={id.includes('@') && pw.length >= 5}
수정했습니다

2022-05-26 01:59 UTC, younuk23 requested changes

2022-05-26 01:59 UTC, younuk23 commented on src/pages/Login/Login.js
> +          disabled={id.includes('@') && pw.length >= 5 ? false : true}
```suggestion
          disabled={!(id.includes('@') && pw.length >= 5)}
```
최초에 리뷰 드렸던 부분 인 것 같은데 똑같은 실수로 다시 돌아가시면 안됩니다!!

2022-05-26 01:59 UTC, younuk23 commented on src/pages/Login/Login.js
> +          disabled={id.includes('@') && pw.length >= 5 ? false : true}
빨리 만들어서 기능 많이 치는게 중요한게 아니라 하나를 하더라도 더 많은 걸 얻어가는 것에 중점을 두고 진행해주세요

2022-05-26 07:14 UTC, younuk23 approved these changes
LGTM 👍

2022-05-26 07:15 UTC, merged