[33기 염종은]ADD:signup 페이지 구현 중
wecode-bootcamp-korea/33-1st-crowsSeven-frontend pull request #9
Opened 2022-05-25 04:48 UTC by Yumjong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
signup 페이지 구현 중 
동의 창 전체 동의 구현
잘 못된 정보 입력하면 경고창 띄우기
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.동의 창 전체 동의 구현 하기
-동의 창에 전체 동의를 누르면 다른 도의 창의 check박스가 checked로 변경
-동의 창에 하나라도 check를 풀면 전체동의 창에 checked도 풀리도록

2. 잘 못된 정보 입력하면 경고창 띄우기
-회원가입시 잘 못된 정보를 입력하면 그 값을 보고 경고창에 경고메세지가 나오도록 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-실제 회원가입의 조건을 생각하고 세밀하게 다룰 수 있다. 조건을 생각해서 거기에 맞는 로직을 짤 수 있다

<br />

## :: 기타 질문 및 특이 사항

2022-05-25 07:44 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!

2022-05-25 07:44 UTC, younuk23 commented on src/pages/jongeun/Signup.js
> +const Signup = () => {
폴더구조는 이름이 들어가는 것이 아니라, 페이지의 이름이 들어가야됩니다
`src/pages/signup` 이 되는것이 맞겠네요 혹시 팀 전체적으로 잘못 이해하고 이렇게 진행하고 있다면 팀원한테 이 내용 공유해주세요!

2022-05-25 07:44 UTC, younuk23 commented on src/pages/jongeun/Signup.js
> +import { Catalogues } from './mock';
정적인 데이터로 보이네요 이경우엔 어떤 것을 모방하는 mock이 아니라 상수데이터가 맞아보이네요 이름 변경해주세요, 애초에 파일이름이 mock인것보다는 어떤 것을 mocking 하는 것인지, 어떤 데이터를 표현하는 것인지 파일명에서 드러나는게 좋겠네요!

2022-05-25 07:44 UTC, younuk23 commented on src/pages/jongeun/Signup.js
> +  }, []);
여기서 list는 변하지 않는 값인 것 같네요, 변하지 않는 값은 state로 관리할 필요가 없습니다.
왜 그런지 한번 고민해보시고 생각하신 것 코멘트로 남겨주세요!

2022-05-25 07:44 UTC, younuk23 commented on src/pages/jongeun/mock.js
> +export const Catalogues = [
상수데이터는 UPPERCASE + snake_case 로 작성해주는게 프로그래밍 컨벤션입니다!! 다른 개발자들이 봤을 때 이 값은 상수값이구나 라고 이해할 수 있게 컨벤션 잘 지켜서 작성해주세요!!

2022-05-25 07:44 UTC, younuk23 commented on src/pages/jongeun/Signup.scss
> +  }
동일한 css를 여러 className에 공통적으로 부여한 모습이 반복적으로 보이는데 동일한 스타일을 부여할 것이라면 하나의 className에  css를 작성하고 해당 className을 활용하면 됩니다.

className을 부여하는 이유는 스타일링을 하기 위함이지 요소들을 이름짓기 위함이 아닌것을 생각해주세요 나중에 스타일링을 수정해야 할 일이 있을 때 중복된 내용이 여러번 작성된 코드와, 공통적인 부분을 한번에 작성한 코드 중 어떤 것이 더 수정하기 용이한지를 고민해보시면 좋습니다.

```js
// bad

// JSX
<input className="id" />
<input className="pw" />
<input className="pwCheck" />

// CSS
.id {
  width:100px;
}

.pw {
  width:100px;
}

.pwCheck {
  width:100px;
}
```

```js
// Good

// JSX
<input className="userInput" />
<input className="userInput" />
<input className="userInput" />

// CSS
.userInput {
  width:100px;
}
```

2022-05-25 08:28 UTC, Yumjong commented on src/pages/jongeun/Signup.js
> +const Signup = () => {
수정했습니다

2022-05-25 08:55 UTC, Yumjong commented on src/pages/jongeun/Signup.js
> +  }, []);
잘 변하지 않는 값은 상수 데이터로 하드 코딩 할 필요 없이 유지 보수하기 위해 만들어 주는 것인데 
잘 변하지 않는 값은 굳이 state에 저장해서 쓸 필요가 없습니다 state는 자주 바꿔주는 값을 넣는 것이 효율적입니다

2022-05-25 09:08 UTC, Yumjong commented on src/pages/jongeun/Signup.js
> +import { Catalogues } from './mock';
수정했습니다.

2022-05-25 09:08 UTC, Yumjong commented on src/pages/jongeun/mock.js
> +export const Catalogues = [
넵 수정했습니다

2022-05-25 09:09 UTC, Yumjong commented on src/pages/jongeun/Signup.scss
> +  }
수정해 보았습니다

2022-05-26 02:01 UTC, younuk23 requested changes
마이너한 부분 리뷰 코멘트 하나 있습니다 이 PR은 머지하겠습니다 코멘트 드린 부분은 다른 브랜치에서 같이 반영해주세요!

2022-05-26 02:01 UTC, younuk23 commented on src/pages/Signup/Signup.scss
> +@import 'src/styles/variables.scss';
variables import 할 필요 없습니다!

2022-05-26 02:02 UTC, younuk23 commented on src/pages/jongeun/Signup.js
> +  }, []);
👍

2022-05-26 02:02 UTC, merged